version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout 
      - run:
          name: build nightly
          command: |
              export DATETAG=`date +%Y-%m-%d`
              docker login -u $DOCKERUSR -p $DOCKERPWD
              docker build --tag=nightly .
              docker run latest perl6 -v
              if [[ "$?" == "0" ]]; then
                echo "DATETAG: $DATETAG"
                docker tag nightly tonyodell/rakudo-nightly:latest
                docker tag nightly tonyodell/rakudo-nightly:$DATETAG
                docker push tonyodell/rakudo-nightly:latest
                docker push tonyodell/rakudo-nightly:$DATETAG
                exit "$?"
              else
                exit 1
              fi
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "10 20 * * *"
          filters:
            branches:
              only:
               - master
    jobs:
      - build
